#!/usr/bin/env python3
"""Regenerate the deterministic, non-secret packaged reference example.

The private keys are deterministically derived solely so the public example can be
regenerated byte-for-byte.  They are test fixtures and must never be used for real
signing or as a source of randomness.
"""
from __future__ import annotations

import hashlib
import json
import sys
from pathlib import Path

from cryptography.hazmat.primitives.asymmetric.ed25519 import Ed25519PrivateKey

ROOT = Path(__file__).resolve().parent
SRC = ROOT / "src"
sys.path.insert(0, str(SRC))
from cases import event  # noqa: E402
from reference_profile import (  # noqa: E402
    certificate_bytes,
    issue_reference_certificate,
    public_key_hex,
)


def fixture_key(label: str) -> Ed25519PrivateKey:
    seed = hashlib.sha256(("causal-roster-test-only:" + label).encode("ascii")).digest()
    return Ed25519PrivateKey.from_private_bytes(seed)


def build() -> tuple[dict, str]:
    authority = fixture_key("history-authority")
    long_a = fixture_key("long-term-A-a1")
    long_b = fixture_key("long-term-B-b1")
    eph_a = fixture_key("ephemeral-session-1-A")
    eph_b = fixture_key("ephemeral-session-1-B")
    context = {
        "domain": "AMS-CAUSAL-ROSTER-V1",
        "mode": "FRESH",
        "application": "benign-reference-example",
        "session": "session-0001",
        "message": "approve:example-object-17",
        "namespace": "example-roster",
        "events": [
            event("a1", "A", key=public_key_hex(long_a.public_key()), weight=7),
            event("b1", "B", ["a1"], key=public_key_hex(long_b.public_key()), weight=5),
        ],
        "lower": ["a1"],
        "upper": ["a1", "b1"],
        "cut": ["a1", "b1"],
        "profile": [["A", "a1"], ["B", "b1"]],
    }
    certificate = issue_reference_certificate(
        context,
        authority,
        {"a1": long_a, "b1": long_b},
        {"A": eph_a, "B": eph_b},
    )
    return certificate, public_key_hex(authority.public_key())


def main() -> int:
    certificate, authority = build()
    examples = ROOT / "examples"
    examples.mkdir(exist_ok=True)
    (examples / "reference-history-public-key.txt").write_text(authority + "\n", encoding="ascii")
    (examples / "reference-certificate.json").write_bytes(
        certificate_bytes(certificate, authority)
    )
    print("wrote deterministic public example")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
